spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: root
    username: sa
    url: jdbc:h2:mem:mydb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

security:
  jwt:
    secret: "Otter Power"
    expiration:
      token-time: 900000 # 15 min en ms
      refresh-token-time: 86400000 # 24 heures en ms